{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SwitchBot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "battery",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bot",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "温湿度", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "battery",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "f1:0d:3c:84:a3:43" }
     ]
    }
   ]
  },
  {
   "title": "湿度",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "f1:0d:3c:84:a3:43" }
     ]
    }
   ]
  },
  {
   "title": "温度",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "meter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "f1:0d:3c:84:a3:43" }
     ]
    }
   ]
  },
  { "title": "環境センサ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "env",
     "select": [
      [
       { "params": [ "range" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "24:a1:60:46:b1:8a" }
     ]
    }
   ]
  },
  {
   "title": "tvoc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "env",
     "select": [
      [
       { "params": [ "tvoc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "24:a1:60:46:b1:8a" }
     ]
    }
   ]
  },
  {
   "title": "co2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "env",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "24:a1:60:46:b1:8a" }
     ]
    }
   ]
  },
  { "title": "開閉センサ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contact",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "cd:06:a5:80:4f:b5" }
     ]
    }
   ]
  },
  {
   "title": "Go out Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contact",
     "select": [
      [
       { "params": [ "goOutCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "cd:06:a5:80:4f:b5" }
     ]
    }
   ]
  },
  {
   "title": "Number of entrances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "contact",
     "select": [
      [
       { "params": [ "entranceCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "cd:06:a5:80:4f:b5" }
     ]
    }
   ]
  },
  {
   "title": "Button push count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contact",
     "select": [
      [
       { "params": [ "buttonPushCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "cd:06:a5:80:4f:b5" }
     ]
    }
   ]
  },
  {
   "title": "HAL UTC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "contact",
     "select": [
      [
       { "params": [ "halUTC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "cd:06:a5:80:4f:b5" }
     ]
    }
   ]
  },
  {
   "title": "lightLevel",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "contact",
     "select": [
      [
       { "params": [ "lightLevel" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "cd:06:a5:80:4f:b5" }
     ]
    }
   ]
  },
  {
   "title": "PIR State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "contact",
     "select": [
      [
       { "params": [ "ripState" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "cd:06:a5:80:4f:b5" }
     ]
    }
   ]
  },
  {
   "title": "PIR UTC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "contact",
     "select": [
      [
       { "params": [ "ripUTC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "cd:06:a5:80:4f:b5" }
     ]
    }
   ]
  },
  {
   "title": "Hal State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 32 },
   "targets": [
    {
     "measurement": "contact",
     "select": [
      [
       { "params": [ "halState" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "cd:06:a5:80:4f:b5" }
     ]
    }
   ]
  },
  { "title": "人感センサ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "motion",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "c4:d7:37:f2:cf:93" }
     ]
    }
   ]
  },
  {
   "title": "動体検知",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 39 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "motion",
     "select": [
      [
       { "params": [ "ripState" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PIR UTC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 39 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "motion",
     "select": [
      [
       { "params": [ "sinceLastTriggerRipTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "c4:d7:37:f2:cf:93" }
     ]
    }
   ]
  },
  {
   "title": "Light intensity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 39 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "motion",
     "select": [
      [
       { "params": [ "lightIntensity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "c4:d7:37:f2:cf:93" }
     ]
    }
   ]
  },
  { "title": "カーテン", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "curtain",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "e0:2e:30:be:cb:ed" }
     ]
    }
   ]
  },
  {
   "title": "position",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "curtain",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "e0:2e:30:be:cb:ed" }
     ]
    }
   ]
  },
  {
   "title": "lightLevel",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "curtain",
     "select": [
      [
       { "params": [ "lightLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "macaddress", "operator": "=", "value": "e0:2e:30:be:cb:ed" }
     ]
    }
   ]
  }
 ]
}