FROM alpine:3.17
WORKDIR /app
RUN apk add --no-cache git oath-toolkit-oathtool jq curl 
RUN git clone https://github.com/thorsten-gehrig/alexa-remote-control.git
RUN git clone https://github.com/thorsten-gehrig/alexa-remote-control.git
