apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: influxdb-conf
    files:
      - conf/influxdb/influxdb.conf
  - name: store-conf
    files:
      - conf/store/homeiot.yml
  - name: scan-conf
    files:
      - conf/scan/homeiot.yml
