apiVersion: v1
kind: Service
metadata:
  name: homeiot-service
spec:
  type: NodePort
  selector:
    app: homeiot
  ports:
    - name: nodered
      port: 1880
      nodePort: 31880
    - name: grafana
      port: 3000
      nodePort: 32000
